fix: remove compiling on macos aarch64 for github actions
looks like meowhash does not support osx aarch64
```
error[E0412]: cannot find type `Simd128` in this scope
Error:    --> /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/meowhash-0.3.0/src/lib.rs:118:12
    |
118 |     regs: [Simd128; 8],
    |            ^^^^^^^ not found in this scope

error[E0412]: cannot find type `Simd128` in this scope
Error:    --> /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/meowhash-0.3.0/src/lib.rs:118:12
    |
118 |     regs: [Simd128; 8],
    |            ^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
117 | pub struct MeowHash<Simd128> {
    |                    +++++++++

error[E0425]: cannot find value `MEOW_PREFETCH_LIMIT` in this scope
```